# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=1.20.6
neo_version=20.6.72-beta
neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
mod_group=com.mrbysco.groomba
mod_id=groomba
mod_archive_name=Groomba

#Publishing
mod_name=Groomba
curseforge_id=525546
modrinth_id=H3O3Y64N

# Version
version=0.1.0

# Dependencies
jei_version=17.3.0.49