modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Groomba/issues"
license="MIT"

[[mods]]
modId="groomba"
version="${file.jarVersion}"
displayName="Groomba"
displayURL="https://www.curseforge.com/minecraft/mc-mods/groomba"
authors="Mrbysco"
description='''
Groomba adds a Roomba like robot that will cut your grass
'''
[[dependencies.groomba]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.groomba]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.117-beta,)"
ordering="NONE"
side="BOTH"