modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/Groomba/issues"
license="MIT"

[[mods]]
modId="groomba"
version="${file.jarVersion}"
displayName="Groomba"
displayURL="https://www.curseforge.com/minecraft/mc-mods/groomba"
authors="Mrbysco"
description='''
Groomba adds a Roomba like robot that will cut your grass
'''
[[dependencies.groomba]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21.5,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.groomba]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.5.0-beta,)"
ordering="NONE"
side="BOTH"